/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Result;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-10-13T15:16:37.985Z[GMT]")
@Api(value = "{a}", description = "the {a} API")
public interface AApi {

    @ApiOperation(value = "", nickname = "aBGet", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 404, message = "404 response") })
    @RequestMapping(value = "/{a}/{b}",
        method = RequestMethod.GET)
    ResponseEntity<Void> aBGet(@ApiParam(value = "",required=true) @PathVariable("a") String a,@ApiParam(value = "",required=true) @PathVariable("b") String b);


    @ApiOperation(value = "", nickname = "aBOpGet", notes = "", response = Result.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "200 response", response = Result.class) })
    @RequestMapping(value = "/{a}/{b}/{op}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Result> aBOpGet(@ApiParam(value = "",required=true) @PathVariable("a") String a,@ApiParam(value = "",required=true) @PathVariable("b") String b,@ApiParam(value = "",required=true) @PathVariable("op") String op);


    @ApiOperation(value = "", nickname = "aGet", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 404, message = "404 response") })
    @RequestMapping(value = "/{a}",
        method = RequestMethod.GET)
    ResponseEntity<Void> aGet(@ApiParam(value = "",required=true) @PathVariable("a") String a);

}
