/*
 * SimpleCalcAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * Input
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-13T16:08:05.207Z[GMT]")
public class Input {
  @SerializedName("a")
  private BigDecimal a = null;

  @SerializedName("b")
  private BigDecimal b = null;

  @SerializedName("op")
  private String op = null;

  public Input a(BigDecimal a) {
    this.a = a;
    return this;
  }

   /**
   * Get a
   * @return a
  **/
  @Schema(description = "")
  public BigDecimal getA() {
    return a;
  }

  public void setA(BigDecimal a) {
    this.a = a;
  }

  public Input b(BigDecimal b) {
    this.b = b;
    return this;
  }

   /**
   * Get b
   * @return b
  **/
  @Schema(description = "")
  public BigDecimal getB() {
    return b;
  }

  public void setB(BigDecimal b) {
    this.b = b;
  }

  public Input op(String op) {
    this.op = op;
    return this;
  }

   /**
   * Get op
   * @return op
  **/
  @Schema(description = "")
  public String getOp() {
    return op;
  }

  public void setOp(String op) {
    this.op = op;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Input input = (Input) o;
    return Objects.equals(this.a, input.a) &&
        Objects.equals(this.b, input.b) &&
        Objects.equals(this.op, input.op);
  }

  @Override
  public int hashCode() {
    return Objects.hash(a, b, op);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Input {\n");
    
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    b: ").append(toIndentedString(b)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
